apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-jgroups-kubeping-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-jgroups-kubeping-pod-reader
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-jgroups-kubeping-service-account
  namespace: {{ .Release.Namespace }}
