apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-files
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: {{ .Values.structr.filesvolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.structr.filesvolume.size }}
