apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-jgroups-kubeping-service-account
      containers:
      - name: {{ .Release.Name }}
        image: structr/structr:5.0.0
        #imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: "/structr/health"
            port: 80
          failureThreshold: 60
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: "/structr/health"
            port: 80
          failureThreshold: 300
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: "/structr/health/ready"
            port: 80
          periodSeconds: 1      
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: REPLICA
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        {{- range $key, $val := .Values.structr.env }}
        - name: {{ $key }}
          value: {{ $val | quote}}
        {{ end }}
        volumeMounts:
        - mountPath: /var/lib/structr/bin/memory.config
          name: {{ .Release.Name }}-memory-config
          subPath: memory.config
        - mountPath: /var/lib/structr/structr.conf
          name: {{ .Release.Name }}-structr-conf
          subPath: structr.conf
        - name: {{ .Release.Name }}-license-key
          mountPath: /var/lib/structr/license.key
          subPath: license.key
        - name: {{ .Release.Name }}-files
          mountPath: /var/lib/structr/files
      imagePullSecrets:
        - name: github-container-registry-access
      volumes:
      - name: {{ .Release.Name }}-memory-config
        configMap:
          name: {{ .Release.Name }}-memory-config
      - name: {{ .Release.Name }}-structr-conf
        configMap:
          name: {{ .Release.Name }}-structr-conf
      - name: {{ .Release.Name }}-license-key
        configMap:
          name: {{ .Release.Name }}-license-key
          items:
          - key: license.key
            path: license.key
      - name: {{ .Release.Name }}-files
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-files

