apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    {{ if .Values.svc.annotations }}
    {{ range .Values.svc.annotations }}
    {{ . -}}
    {{ end }}
    {{ end }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  selector:
    app: {{ .Release.Name }}
