# configure the desired number of replicas
replicaCount: 1

# Structr configuration
structr:

  # configure your desired memory limits
  memory:
    min: 1g
    max: 4g

  # configure the storage class and size for your cloud provider of choice
  filesvolume:
    storageClassName: "standard"
    size: 2Gi

  # configure the connection to Neo4j
  config:
    database: 
      url: "bolt://neo4j:7687"
      username: "neo4j"

    # Add custom config entries here
    custom: [
      # Allow Structr apps to be auto-migrated across multiple versions
      "application.schema.automigration = true",
      # Enable/Disable cluster mode for Structr
      "application.cluster.enabled = false",
      # Explicitly enable MetricsServlet for Prometheus scraping
      "httpservice.servlets = JsonRestServlet HtmlServlet WebSocketServlet CsvServlet UploadServlet ProxyServlet GraphQLServlet DeploymentServlet LoginServlet LogoutServlet TokenServlet HealthCheckServlet HistogramServlet OpenAPIServlet FlowServlet MetricsServlet"
    ]

  # put the contents of your license.key file here
  # please note that clustering only works with a Structr Enterprise license key
  license: ""

# configure resource limits according to you cluster node configuration
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 1Gi

svc:
  annotations: [
    # add custom annotations for svc
    
  ]